## Remote package repositories
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.7/targets/armsr/armv8/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_generic/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.7/targets/armsr/armv8/kmods/6.6.141-1-2a67cc4ae7b7c1f0c3b665bec0c6f387
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_generic/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_generic/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_generic/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.7/packages/aarch64_generic/telephony


## This is the local package repository, do not remove!
src imagebuilder file:packages
option check_signature
