## Remote package repositories
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.8/targets/armsr/armv8/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.8/packages/aarch64_generic/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.8/targets/armsr/armv8/kmods/6.6.144-1-0b532dfcba2e5fa16405c5387dd37cae/
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.8/packages/aarch64_generic/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.8/packages/aarch64_generic/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.8/packages/aarch64_generic/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.8/packages/aarch64_generic/telephony


## This is the local package repository, do not remove!
src imagebuilder file:packages
option check_signature
